[build]
  command = "npm run build"
  publish = "_site"
  functions = "functions/active"

  [build.environment]
    NODE_VERSION = "20"


[dev]
  command = "npm run serve"
  port = 8888
  targetPort = 8080
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  included_files = [
    "functions/util/**",
    "src/_data/site.json",
    "src/_data/judges.json",
    "src/_data/lawyers.json",
    "src/_data/law_firms.json",
    "src/_data/courtrooms.json",
  "src/_data/expense_types.json",
  "src/_data/hearing_types.json"
  ]
